### ISSUE TITLE
max.db.json construction missing the (sub)objects of fluid.libmanipulation.mxo that do not have a <dump> method

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-docs#11]
is there somewhere we need to add it manually? everything else seems to be found in Max7 and 8, I've rebuilt the database, and the ref is definitely there in the folder..

**Comment by weefuzzy** [comment]
Are you getting a new 
build/interfaces/flucoma-obj-qlookup.json
build/interfaces/max.db.json
generated when you build? 

* They should have an up to date list of all the objects 
* They should be copied up into /interfaces as part of the install step.

**Comment by jamesb93** [comment]
IIRC from doing FrameLib the reference should work automatically if there is a .maxref.xml with the corresponding name inside Package/docs. 

You don't need the qlookup or the max.db.json stuff afaik but I'm ready to be corrected 🤓

**Comment by weefuzzy** [comment]
qlookup, iirc, gets you entered into the object launcher, or whatever it's called 

max.db.json makes sure the objects appear in the *search* in the reference interface (e.g. if you start typing the name into the address bar)

**Comment by jamesb93** [comment]
That sounds right. I think if you right click the object and ask for the reference it just looks for the .maxref so its worth pinning down which bit of the docs feels broken @tremblap

**Comment by weefuzzy** [comment]
I'm interpreting "does not appear in the reference search" as to do with the json files, because IIRC that was the feature request that led to them getting generated in the first place

**Comment by tremblap** [comment]
the files are there. the stuff is new and put in interface. I can even find the object's reference by right-clicking the object.

What doesn't work is, as I said in the title, the search of reference. Add to this that autocomplete does not find fluid.grid~

That is all true for Max 7 only now. Now max 8 finds it after a restart of the computer. This is surreal.

**Comment by weefuzzy** [comment]
> I can even find the object's reference by right-clicking the object.

This depends on whether the `.maxref` exists, not on whether there's an entry in the max.db.json (which is what Max 7, but not 8, depends on for searchability). 

Have you rebuilt the Max 7 db?

**Comment by tremblap** [comment]
A new 'feature' of Max8 is that since I recompiled the doc (and the new cmake, it might be that) Max refuses to quit. I have to finish with a force-quit. I wonder if that is the new doc, or the new cmake compile messing something. I will switch to the latest public, reboot, and see if that happens. If not, I'll replace the doc with the old one and see if that happens. If not we kno it's the doc.

**Comment by tremblap** [comment]
ok, this is fun.

Something breaks max8 silently (refusing to finish to quit) and max7 (not finding the ref in the search nor autocomplete) in the tip of doc+max - everything works fine with the last public release. Next step, replace the doc only from the release. I expect grid not to be found but at least Max to quit properly.

**Comment by tremblap** [comment]
so, new compiles with old doc is working and quiting fine. Now, I'll recompile the doc put it at the right place and see

**Comment by tremblap** [comment]
ok now it is a little saner. Max7 does not autocomplete fluid.grid~ nor find it in the reference search, but max8 behaves. I wonder if the construction of interfaces/flucoma-obj-qlookup.json and its buddy max.db.json is not faulty. I find grid in the former but not in the latter.

**Comment by weefuzzy** [comment]
The problem here is that the code that generates `max.db.json` only tries (and needs) to gather together those objects in `fluid.libmanipulation.mxo` and was testing for the existence of a `dump` message as a common trait of all these objects, but `fluid.grid~` doesn't have a `dump` message. So I'll need to go back to the drawing board for how to capture that. 

The reason we need this is because in Max 7 (not 8), the reference search can't find objects mapped to a different external without the aid of this additional json file. 

Happy enough for this to be labelled a bug, if the title is changed to say what needs fixing now that we know.

**Comment by tremblap** [comment]
changed, made explicit.

Another option is to add <dump> to grid, which would make sense. I am also tempted to add the max values for each dimension and dump would be handy there too. Nevertheless, other objects are likely to be missed so this renamed bug still stands.
