### ISSUE TITLE
SuperCollider BufNMF example code doesn't demonstrate resynthMode

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-docs#115]
As the title suggests, it should be updated to reflect the new `resynthMode` parameter.

**Comment by tedmoore** [comment]
Is this referring to the RST or the SC example code? The RST should render into the schelp file format with the rest of the parameters.

**Comment by jamesb93** [comment]
ATM Max gets `resynthMode` in the reference, autocomplete etc.

SuperCollider doesn't have this because it is not in the documentation:

https://github.com/flucoma/flucoma-docs/blob/main/doc/BufNMF.rst

**Comment by tedmoore** [comment]
I see, isn't it also true then that Max has no description of `resynthMode`? Just that it shows up as a possible parameter because it get's pulled from the c++?

**Comment by jamesb93** [comment]
That is true. I wanted to flag it here because you had finished the NMF supercollider examples which as it stands don't account for the new default behaviour of not resynthesising.

**Comment by jamesb93** [comment]
I haven't gotten to BufNMF yet
