### ISSUE TITLE
`fluid.mlpregressor~` should be explicit about which `@activation` is which

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-docs#125]
The helpfile simply has text stating:
![Screenshot 2022-05-24 at 2 31 41 pm](https://user-images.githubusercontent.com/2747015/170047431-6168e903-499e-438f-b943-c362daace599.png)

Aside from "beware" being an odd word choice here, it would be great to be explicit since the `@activation` attribute takes an `int` rather than a `symbol` (e.g. `@activation sigmoid`, which wouldn't be a bad idea).

Something like:
```
The activation function to use for the hidden layer units. Be aware of the permitted ranges of each, although (blah blah blah - I remember something Owen said about it still wanting to converge either way)

1. relu (0->inf)
2. sigmoid (0->1)
3. tanh (-1,1)
```

**Comment by jamesb93** [comment]
The formatting for this is now fixed.
