### ISSUE TITLE
`@padding` attribute in reference documents is a super long single paragraph (confusing)

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-docs#126]
When looking at the `@padding` section of the reference file of any of the objects (e.g. `fluid.bufmelbands~` or `fluid.bufmfcc~`) you are greeted with a single run-on paragraph:
![Screenshot 2022-05-21 at 11 30 31 pm](https://user-images.githubusercontent.com/2747015/169670964-80d1dbfb-e826-4712-8f83-821c02735bef.png)

This takes me a bit to read through everything as there's loads of brackets and hyphens and such. As compared to the `@fftsettings` attribute, which has line breaks, and even bullet points:
![Screenshot 2022-05-21 at 11 29 51 pm](https://user-images.githubusercontent.com/2747015/169670940-d92c09fd-84b1-49f3-9793-1212dcbb84a6.png)

Something with a similar structure would be useful.

**Comment by jamesb93** [comment]
Solved in #154
