### ISSUE TITLE
Multiple typos in `fluid.bufampgate~` reference file

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-docs#139]
If there's a couple here, there's probably more elsewhere. Would be worth running all the text through a spell check separately from Max.

![Screenshot 2022-05-25 at 11 03 16 am](https://user-images.githubusercontent.com/2747015/170237353-b94e1092-bcd5-4d34-828a-fecf21dcd975.png)

It's an "envelopE" follower, and a "[Schmitt](https://en.wikipedia.org/wiki/Schmitt_trigger)" trigger.

**Comment by tremblap** [comment]
most of them are corrected in @tedmoore PR's https://github.com/flucoma/flucoma-docs/pull/122

**Comment by tedmoore** [comment]
@tremblap  Is this closable?

**Comment by tremblap** [comment]
probably - @rconstanzo might want to check as the originator

**Comment by rconstanzo** [comment]
My comments (for this one) were just the typos, which I presume were sorted as they are quite easy fixes. So close time it is!
