### ISSUE TITLE
NMFMatch SC example code: `A pick compressor` not working

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#144]
The example code with the heading, "A pick compressor" in the SuperCollider NMFMatch help file doesn't seem like it sounds how it is supposed to. It just outputs a few little blips, when I think it is supposed to sound more like a guitar!

(this ticket is flagged in this repo because this is where that file lives).

**Comment by tremblap** [comment]
it used to work so I reckon we could just put the old code in?

**Comment by tremblap** [comment]
(it is probably quite ugly though :) )

**Comment by tedmoore** [comment]
It worked when I adapted the code as well. I was thinking maybe it is not working anymore due to an interface change that has happened in the mean time. Or perhaps another kind of bit rot. I just made a ticket to remind us to check up on it!
