### ISSUE TITLE
Towards producing SC docs 

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-docs#15]
@tedmoore @jamesb93 pinged me on e-mail asking how hard it would be / how advanced current work is towards having the current system produce our SC documentation as well as that for the other platforms. I'm opening this as a visible / audit-able place to thrash through the current state of things, and plan steps forward. 

#### More General Review Needed
As a meta-issue, and important background, this whole repo is well overdue a code review. What started as an ad hoc solution to producing the XML for Max reference docs from a combination of scraped meta-data and human documentation has acquired several layers of band-aids, and the whole thing is now quite creaky. Just skimming the existing code for a few minutes has revealed all sorts of crimes, and eye watering nasties.

Work at some point started on seeing if more of what we do here could be delegated to something that already exists, like Sphinx, but inconclusively. 

#### Currently, though 

The (pretty baroque) way that things work is that we have some JSON files that are generated in C++, and compile information about `Client`s' interfaces (parameters, messages and so forth), and we have YAML files that provide documentation blocks for each component of the interfaces, and the blocks themselves use RST markup 😬 . A Python script then combines these, and uses Jinja to produce XML / HTML for Max / PD / CLI. The YAML files of human written docs typically start life as SC documentation that is copied over (tedious and error-prone, hence this discussion) 

To make life more horrible, documentation for some bits of interfaces that are common across clients (e.g. FFT settings, are basically baked into code. Sometimes in the Python. Sometimes in the Jinja template. Don't @ me.)

#### What's needed for SC? 

In addition to a Jinja template(s), SC introduces an additional complication relative to Max/PD/CLI, insofar as the blocks of documentation from the YAML would need to be transcoded from RST to SCDOC syntax. For the other CCEs we're using docutils, which has a built-in writer for HTML, whereas here we need to roll our own 'translator' that converts docutils nodes to scdoc. We then also need a Python script, or to update the existing script. 

I seem to have locally the start of work on this, in the form of a RST->SCDOC writer, and a Python script, and I've put these on a topic branch https://github.com/flucoma/flucoma-docs/tree/enhance/sc-update

I suspect that what will give us some problems is that the SC classes are made by humans, so might not benefit from the same total-predictability of interface that we have elsewhere. That said, the existing code is already hampered by the growing complexity of if-buts, exceptions and what have you (which returns me to the need for a more general review).

Anyway: simplest case is that what is on that branch substantively works, and that working out the various Jinja templates needed to cover our current SC needs turns out to be Not So Bad.

**Comment by tedmoore** [comment]
Ok, I dipped a toe in here:

https://github.com/flucoma/flucoma-docs/blob/enhance/sc-update-yaml/create_schelp/create_schelp.py

Seems ok so far. I will probably be needing to pull more info from the jsons and maybe also the ... xml 😬 ... but if anyone @weefuzzy @jamesb93 @tremblap wants to take a look over and see if there are any obvious problems I'll run into, that would be appreciated.

After this brief experiment, it seems to me that this would be a time saver in the long run. Do others agree?

**Comment by jamesb93** [comment]
This is a good start IMO and I'd have to take a look at what the relationship between input and output is to see how its managing. One thing I noticed is that the treatment of paths is quite brittle and potentially not cross platform. You should leverage the `pathlib` module to form the paths and convert them to string if you need to at the very last moment.

```py
yaml_path = os.path.dirname(filepath) + f'/../../doc/{name}.yaml'
```

would become something like:

```py
from pathlib import Path


yaml_path = Path(filepath) / Path(f'../../doc/{name}.yaml')
```

That is python without checking so maybe wrong, but the underlying message is the same in that f-strings should not be responsible for forming the paths, and `pathlib` should be to ensure its both cross platform as well as more likely to compose a path that exists on the filesystem. It should also allow you to store the re-usable bits as variables and concatenate paths in a more readable way down the line.

While we're here we should also add types to all the arguments so in the future its. bit easier to know if something like `filepaths` is an array of `pathlib` objects, strings etc etc. I think that this is important for the longevity of the code.

Also what are you plans for embedding the help code at the bottom? Seems like you can just continue on trend and write line-by-line for it?

Also why might you need to dig into the XML? Is it for the "Class Methods" part?

**Comment by tedmoore** [comment]
> You should leverage the `pathlib`
> add types to all the arguments

Yes cool, will do.

> what are you plans for embedding the help code at the bottom

Yeah, as I said previously, i'm planning to have it in a separate .scd file and then just read it into the .schelp file

> why might you need to dig into the XML? Is it for the "Class Methods" part

I'm kind of juggling the three files (YAML, JSON, XML) to get at what I need... hopefully just two of these will cover everything.

**Comment by weefuzzy** [comment]
Thanks for making a start on this. I'd suggest that 

* using a Jinja template to build up the schelp file, like we do for the other platforms, will be much cleaner
* using the existing Python script has the benefit of doing a (great deal) of error checking (although it might be that this script is overdue some refactoring and tidying up) 
* that python script also has a start on converting inline restructured text formatting from the yaml files into scdoc format 

A tricky bit might be inferring the quantities of I/O on objects' ar / kr methods, because these aren't explicitly documented at the moment AFAIK

**Comment by tedmoore** [comment]
@weefuzzy I'm quite hesitant to dive into Jinja as I've never used it before and I am worried that learning that framework will take too much of my time. I took a look at the existing Python script and I don't feel prepared to parse that or tidy it on my own, so if you think that offering a walkthrough would be possible fruitful, I'd be down for that. I also don't want to commandeer your time.

I'm trying to figure out how to best conserve our time going forward. My gut says that having this automated will save time in the long run and if I'll be implementing and managing the script I want it to be something that I know the ins and outs of so it is simple for me. But maybe the Jinja thing will be simpler for me in the long run?

**Comment by weefuzzy** [comment]
It's certainly not your problem to tidy up the python as it stands, however doing a completely independent run on producing SC doc isn't going to save time in the short or longer-term: you will run into troublesome cases almost immediately (e.g. properly documenting FFT parameters), and having a basically separate framework for the SC doc is going to reproduce some of the same problems we already have. 

Between you, I and @jamesb93 we have the chops to tackle this. James is familiar with jinja, and has already suffered the psychic trauma of looking at the python. So I'd suggest we proceed tentatively as a trio, building up a list of issues with the python as we go.

**Comment by jamesb93** [comment]
Maybe this requires a more Death Star approach. I imagine we are each one of the beams that meet in the middle and destroy Coruscant, thus ending the rebellion.

Perhaps it would be good to spark a meeting and set an agenda. I have an idea about what the quirks are of docs as it stands and where we could do better and in so far as my own calendar goes adding some coding time dedicated to this would not be unreasonable or far away from my current work of pimping learn as hard as I can until something more pressing gets in the way.

What do you guys think?

**Comment by weefuzzy** [comment]
Yes, a meeting sounds like a good idea, and  always up for a collaboration structured by a good Star Wars analogy. 

As you've already discovered, there's a lot of dusty corners in the code as it is, and we've transitioned quite suddenly from it being something that's been kept just viable for doing its job to something that other human beings are interested in reading and extending. 

Given that the job(s) it needs to fulfil aren't all straightforward and obvious, a quick chin wag to crystallise how we're variously positioned to contribute to improvements will help to make sure we don't waste any effort.
