### ISSUE TITLE
JSON files not being created

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#19]
Greetings,

This seems to be running  fine--it creates a `json` folder but doesn't put anything in it. What am I missing?

I'm assuming that `-DFLUID_PATH=` should point to the `flucoma-core` repo?

At the `make` stage, it is giving me a lot of warnings that look like this:
```
/Users/macprocomputer/Desktop/_flucoma/code/flucoma-core-src/include/clients/rt/../common/../../algorithms/public/../util/SpectralEmbedding.hpp:38:10: warning: unused variable 'nConverged' [-Wunused-variable]
    auto nConverged = eig.compute(
         ^
In file included from /Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/src/clients/AmpGate/AmpGate.cpp:12:
/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/src/clients/AmpGate/../../../include/FluidParameterDump.hpp:261:20: warning: unused parameter 'p' [-Wunused-parameter]
  makeValue(Param& p)
```

Thank you!

**Comment by weefuzzy** [comment]
Those warnings aren't anything to worry about – I'll zap them in due course. Looks like the target for making the JSON isn't running, which it might not if you're building this in isolation (the only use case I've really tested is using it alongside Max or PD builds)

**Comment by weefuzzy** [comment]
Running `ninja  MAKE_MAX_REF` should produce the JSON though

**Comment by tedmoore** [comment]
Ok, finally catching up on this. I'm hoping to take a brief crack at the "auto-SC-docs" idea this week before plunging into the help files activities.

`ninja MAKE_MAX_REF` produces this error for me:

ninja: error: loading 'build.ninja': No such file or directory

I tried it before and after `make`.

What am I missing? @weefuzzy @jamesb93 Thank you!

**Comment by jamesb93** [comment]
You will need to specify the build tool you want to use in the cmake generation.

so:

`cmake -GNinja -DDOCS=ON -DMAX_SDK_PATH=../sdk ..`

I think this is the most minimal command you can possibly do for Max and you would have to replace `-DMAX_SDK_PATH=../sdk` with the correct path to the Max 8.2 SDK.
