### ISSUE TITLE
Bug: FluidLoudness RST has copy-paste error

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#194]
### Please tell us what you were doing! You can include code and files by drag and dropping them into the text area.

The SC FluidLoudness helpfile says it Returns "A 2-channel KR signal with the [pitch, confidence] descriptors. The latency is windowSize." which is a copy-paste error from FluidPitch. 

This will need to be edited in the RST file containing the information for FluidLoudness that gets absorbed when building docs for all platforms.

![Screenshot 2023-09-13 at 10 35 36 AM](https://github.com/flucoma/flucoma-docs/assets/1531144/eba38628-4fb4-457f-8ad8-d39227961143)

### What was the expected result?

n/a

### What was the actual result?

n/a

### What operating system were you using?

Mac

### Operating system version

mac os ventura 13.5.2

### FluCoMa Version

1.0.6+sha.386d174.core.sha.f694a366

**Comment by tremblap** [comment]
fixed thanks
