### ISSUE TITLE
Problems compiling with -DDOCS=ON

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-docs#21]
Configuring CMake works in the build directory by running something like:

`cmake -GNinja -DFLUID_PATH=../../core -DDOCS=ON ..`

However, calling `ninja` afterwards produces this error:

```
[0/2] Re-checking globbed directories...
ninja: error: 'MAKE_CLI_REF', needed by 'CMakeFiles/CLI_MAKE_DOCS', missing and no known rule to make it
```

I've torn my hair out a bit searching for how the other environments deal with it and I can't see a difference... Max's counterpart is even directly commented out https://github.com/flucoma/flucoma-max/blob/5dbca51bbab24cd0861456cea5043c887457c3f6/CMakeLists.txt#L96. I would try to solve this one but any chance you take a look for me @weefuzzy . My CMake-fu is pushed beyond its limits 😿

**Comment by weefuzzy** [comment]
Now uncommented. See if that helps

**Comment by jamesb93** [comment]
It does indeed help. New issue incoming though....

**Comment by jamesb93** [comment]
oops no:

```
FAILED: _deps/flucoma-docs-build/CMakeFiles/MAKE_CLI_REF /Users/james/dev/flucoma/cli/build/_deps/flucoma-docs-build/CMakeFiles/MAKE_CLI_REF 
cd /Users/james/dev/flucoma/cli/build/_deps/flucoma-docs-build && /opt/homebrew/Cellar/cmake/3.22.0/bin/cmake -E make_directory "" && /usr/local/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Users/james/dev/flucoma/docs/script/MakeRef.py cli /Users/james/dev/flucoma/cli/build/json /Users/james/dev/flucoma/docs/doc "" /Users/james/dev/flucoma/docs/script/templates
Error creating directory "".
ninja: build stopped: subcommand failed.
```

**Comment by jamesb93** [comment]
Yep I had a dig and thought maybe MakeRef.py was responsible though I see `cmake -E make_direcotry “”` is called too

**Comment by weefuzzy** [comment]
Ok, I see the problem. Just testing before I push

**Comment by jamesb93** [comment]
You're a gem 💎

**Comment by weefuzzy** [comment]
Try now (or, like, whenever)

**Comment by jamesb93** [comment]
will do later, got a thing now. Exciting! CI might be online 2nite ;)

**Comment by jamesb93** [comment]
Cool this solves this problem. I'm now running into an architecture issue which is likely to be an M1 thing 😔 I think that the docs compile is now picking up the architecture properly or something. Here is my error log:

[error.txt](https://github.com/flucoma/flucoma-docs/files/7679441/error.txt)

**Comment by weefuzzy** [comment]
`Undefined symbols for architecture x86_64:` doesn't look promising. Is this starting with a clean cache?

**Comment by weefuzzy** [comment]
Oh, hold up. I see it. x64 is baked in on Apple 😬 Will remove

**Comment by jamesb93** [comment]
All good. I await your precise and surgical Cmake-fu

**Comment by weefuzzy** [comment]
Pushed. You'll need to clean your cache or whatever before this makes any positive difference

**Comment by weefuzzy** [comment]
Although, I notice we have the same badness in the other sub-repos. Are you not passing a `-DCMAKE_OSX_ARCHITECTURES=arm64` in to cmake?

**Comment by jamesb93** [comment]
Since I've been allowing fat binaries for Max'n'stuff no but I should really...

**Comment by jamesb93** [comment]
Error arises still even after passing `-DCMAKE_OSX_ARCHITECTURES=arm64`

```
FAILED: _deps/flucoma-docs-build/src/clients/BufSines/BufSines 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -stdlib=libc++ -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.8 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  _deps/flucoma-docs-build/src/clients/BufSines/CMakeFiles/BufSines.dir/BufSines.cpp.o -o _deps/flucoma-docs-build/src/clients/BufSines/BufSines  _deps/flucoma-core-build/libHISSTools_FFT.a  -framework  Accelerate  -stdlib=libc++ && :
ld: warning: ignoring file _deps/flucoma-core-build/libHISSTools_FFT.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
```

**Comment by weefuzzy** [comment]
That's flucoma-docs barfing though 😖

**Comment by jamesb93** [comment]
😡 let me know how I can help or test things

**Comment by weefuzzy** [comment]
My bad, insofar as I didn't notice that this was the docs repo to start with (curse all the emails). But now I'm puzzled this doesn't break elsewhere, or is this across Max / PD and CLI?

**Comment by jamesb93** [comment]
Yep its everywhere. I'll chec the linked PR now.
