### ISSUE TITLE
Error in building docs for pure data

### ISSUE THREAD

**Issue by muziker** [flucoma/flucoma-docs#32]
flucoma-docs 1.0.0-TB2.beta4
flucoma-pd 1.0.0-TB2.beta4-1-g91991b1 

Building the documentation results in these errors:

> FluidParameterDump.hpp:325:24: error: incomplete type 'fluid::client::Constraint<fluid::client::FFTParams::FFTSettingsConstrant<2> > ' used in nested name specifier
> 
> FluidParameterDump.hpp:322:5: error: no matching function for call to 'std::initializer_list<int>::initializer_list(<brace-enclosed initializer list>)'

**Comment by weefuzzy** [comment]
That's really weird. I assume you're using GCC – could you paste in the version, and which Linux you're on?  If it's not finding `std::initializer_list`'s default constructor, that smells a bit like the C++ dialect missing from the compiler invocation. 

Presumably, you're just doing the standard recipe 
```bash 
cmake -DDOCS=ON <blah> ..
make
```
?
