### ISSUE TITLE
PureData has tildes in their titles for HTML documentation

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-docs#33]
Some of the objects don't have tildes like Max, but their HTML docs have them.

![image](https://user-images.githubusercontent.com/13281862/149919483-1653a593-d6d9-4e75-a82b-27f9b771fd34.png)

**Comment by weefuzzy** [comment]
Ah, I didn't see this: we'll need to fix up the pd-object-namer

**Comment by tremblap** [comment]
This is fixed by pr#45
