### ISSUE TITLE
[SC] Discrepancy in arguments order: `padding`

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#43]
As seen in the picture below, the order of arguments is different between when the user calls `.kr` and when the arguments actually go to the server. (This is also true for `.process` and `.processBlocking`).

This is a problem because when the docs are built it creates the arguments list based on the ordering in the C++ (which I supposed in this case is the order they get sent to the server), so SCDocs throws an error every time this help file is opened because the Docs order and the object's order are different.

My guess is that changing it in the C++ is nasty and would affect the other CCEs so this should be fixed in SC...which would mean just changing the order of the argument list (and other objects too I believe). I'm happy to do this manually (it's not really that many).

However this would be a breaking change. ...However I think that most users don't specify arguments with out using keywords all the way out to the 7th argument in these cases. Especially because often, the arguments `startFrame, numFrames, startChan, numChans` are left to defaults so the user would need to use keywords after that anyway. So my guess is it very likely not going to break/affect much code at all.

Since this SC docs overhaul is going to have breaking changes like this, perhaps it should try to be aligned with beta5 so that we can alert users?

<img width="705" alt="Screenshot 2022-01-27 at 18 20 53" src="https://user-images.githubusercontent.com/1531144/151459858-16f4463a-40bb-4f91-8aa9-307c704b98bd.png">

<img width="1069" alt="Screenshot 2022-01-27 at 18 33 37" src="https://user-images.githubusercontent.com/1531144/151460843-db7ffb5c-1ef4-4a49-8324-1e7800d69d3d.png">

**Comment by weefuzzy** [comment]
Sounds more like it should be fixed in docs. `padding` is an awkward special-casey  thing that only got added relatively recently, and then only for descriptors. The problem here is that the SC Jinja template / python isn't yet taking account of it. 

If the `species` key in the YAML allows, we may be able to sneak it into the Jinja with a simple conditional. However, IIRC, `FluidLoudness` is a annoying edge case because it's not a FFT based thing, so the surrounding arguments at that end are slightly different.

**Comment by weefuzzy** [comment]
It might be easiest to do this in the python post-verification step. I think the only way we can tell is for `FluidBuf*` objects that have an equivalent `Fluid*` object whose `species` is `descriptor` 😿

**Comment by tedmoore** [comment]
😿 Whoa. Ok, that sounds doable though. I'll take a look at it. I'm gonna wait to hear back on the other PR (https://github.com/flucoma/flucoma-docs/pull/41) and issue (https://github.com/flucoma/flucoma-docs/issues/42). In case your thoughts about that guide the path forward.

**Comment by weefuzzy** [comment]
Oh, it's even worse, upon looking. The index doesn't exist at that point, so the only place we can do cross referenceing is in jinja. Which means a new jinja filter (not terrible), to do the terrible thing.

**Comment by weefuzzy** [comment]
Or, and hear me out here, we just change the `species` key of the relevant object to `buffer-descriptor` (or whatever), so we can then sort this without needing to cross reference. I'd be chill with doing that, because I'm hoping the need for `species` will be short lived 😬

**Comment by tedmoore** [comment]
Yup. Fine by me.

**Comment by tremblap** [comment]
I have no opinion on the best way forward, as long as the main users find it idiomatically sound.

**Comment by weefuzzy** [comment]
I think this might actually be a C++ problem. In my mind, padding was meant to be added at the end of the parameter tuple for those special cases that needed it, but it seems to appear in the middle of the json. I'm going to put this on hold whilst I investigate...

**Comment by weefuzzy** [comment]
Indeed I am inserting it somewhere unhelpful, and I remember why I never wanted to see that code ever again 😭 It's much harder (I think) to put it at the end in C++ (it's a magically generated thing). Will fix in Python, not too complication and – besides – the FFT settings need fixing anyway.
