### ISSUE TITLE
HPSS yaml has many arguments commented out

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#61]
Both the HPSS and BufHPSS yaml files have many arguments commented out (see below). SuperCollider is looking for there to be information about these arguments, so it is complaining. Before I just uncomment these things in an attempt to fix them, I thought I would ask about it, since it seems intentional and there is probably some thought behind it.

Why are these commented out? Can I uncomment it all?

```
# harmThreshFreq1:
  #   description: |
  #     In modes 1 and 2, the frequency of the low part of the threshold for the harmonic filter (0-1)
  # harmThreshAmp1:
  #   description: |
  #     In modes 1 and 2, the threshold of the low part for the harmonic filter. That threshold applies to all frequencies up to harmThreshFreq1: how much more powerful (in dB) the harmonic median filter needs to be than the percussive median filter for this bin to be counted as harmonic.
  # harmThreshFreq2:
  #   description: |
  #     In modes 1 and 2, the frequency of the hight part of the threshold for the harmonic filter. (0-1)
  # harmThreshAmp2:
  #   description: |
  #     In modes 1 and 2, the threshold of the high part for the harmonic filter. That threshold applies to all frequencies above harmThreshFreq2. The threshold between harmThreshFreq1 and harmThreshFreq2 is interpolated between harmThreshAmp1 and harmThreshAmp2. How much more powerful (in dB) the harmonic median filter needs to be than the percussive median filter for this bin to be counted as harmonic.
  # percThreshFreq1:
  #   description: |
  #     In mode 2, the frequency of the low part of the threshold for the percussive filter. (0-1)
  # percThreshAmp1:
  #   description: |
  #     In mode 2, the threshold of the low part for the percussive filter. That threshold applies to all frequencies up to percThreshFreq1. How much more powerful (in dB) the percussive median filter needs to be than the harmonic median filter for this bin to be counted as percussive.
  # percThreshFreq2:
  #   description: |
  #     In mode 2, the frequency of the hight part of the threshold for the percussive filter. (0-1)
  # percThreshAmp2:
  #   description: |
  #     In mode 2, the threshold of the high part for the percussive filter. That threshold applies to all frequencies above percThreshFreq2. The threshold between percThreshFreq1 and percThreshFreq2 is interpolated between percThreshAmp1 and percThreshAmp2. How much more powerful (in dB) the percussive median filter needs to be than the harmonic median filter for this bin to be counted as percussive.
```

**Comment by weefuzzy** [comment]
> Why are these commented out? 

I don't know

> Can I uncomment it all?

Try and see

**Comment by tedmoore** [comment]
I've discovered that the parameters that were commented out in the YAML are not in the JSON generated from the C++ (see below). I wrote a little reverse validator in the python to double check this as well: https://github.com/flucoma/flucoma-docs/blob/7e4ccd5c3bfd5c6ef190fb7bd04af6c85fe7efa8/flucoma/MakeRef.py#L91 So I think the next thing is, @weefuzzy, can you take a look at this for me or point me to where I can debug this?
<img width="300" alt="Screenshot 2022-02-02 at 17 45 45" src="https://user-images.githubusercontent.com/1531144/152250403-acbb4742-a918-4739-8582-998062133582.png">

**Comment by weefuzzy** [comment]
Ah yeah, I see. It's these bad boys here (abridged): 
```json
    { 
      "displayName": "Harmonic Filter Thresholds",
      "name": "harmThresh",
      "size": 4,
      "type": "float"
    },
    {
     
      "displayName": "Percussive Filter Thresholds",
      "name": "percThresh",
      "size": 4,
      "type": "float"
    },
```
Each of these, internally, is a single parameter group together two amplitude-frequency pairs. TBH, I have no memory of who decided these should be split out into 8 separate arguments in sclang, or why. Personally `[[a,f],[a,f]]` seems less gross. 

IAC, fixing it involves detecting these things in the generator and making sure jinja dutifully spews out separate arguments. 

Not clear in my head the best place to do this yet
