### ISSUE TITLE
FluidChroma arguments inconsistent ordering

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#62]
Same issue as / related to: https://github.com/flucoma/flucoma-docs/issues/59
<img width="1177" alt="Screenshot 2022-02-02 at 15 03 43" src="https://user-images.githubusercontent.com/1531144/152228856-5214991e-277f-42ed-bf31-d099160a4c9f.png">

**Comment by tremblap** [comment]
see comment on #59
