### ISSUE TITLE
[SC] Deprecate Guides/FluidDecompositionToolbox?

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#63]
Now that there is the `Fluid Corpus Manipulation Toolkit` guide which has all the things that are also in the older `Fluid Decomposition Toolbox` guide it might actually be confusing for there to be two of them. 

Does it makes sense to delete the old one at this point?

**Comment by weefuzzy** [comment]
yes

**Comment by tremblap** [comment]
go for it, delete away.
