### ISSUE TITLE
BufAudioTransport argument names

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#66]
I'm seeing varying names for BufAudioTransport arguments in different places (JSON, YAML, SC class definition). Sometimes `source1`/`source2` terminology, sometimes `source`/`source2` and sometimes `sourceA`/`sourceB`. Below you can see what is coming out the JSON. 

I prefer the A/B approach because the 1/2 approach could be confusing, given that the `interpolation` parameter is 0-1.

Thoughts? Also, how hard is it to change what the C++ dumps into the JSON so that these can be aligned?

<img width="545" alt="Screenshot 2022-02-03 at 13 04 04" src="https://user-images.githubusercontent.com/1531144/152402536-71a4cb4d-bce9-4f9c-afbf-516ebcb820d6.png">

**Comment by tremblap** [comment]
I agree with you that A-B is much better. We will need to change the C++ but that is no problem. We'll need to flag code-breaking change but now is the time to do them.

**Comment by jamesb93** [comment]
Because there are only ever 2 sources I think A/B works well. I'm relatively indifferent to it though.

**Comment by tedmoore** [comment]
This can be close upon merging:

https://github.com/flucoma/flucoma-sc/pull/62
https://github.com/flucoma/flucoma-docs/pull/69
https://github.com/flucoma/flucoma-core/pull/89
