### ISSUE TITLE
No `enum`s appearing in SC docs

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#84]
argument metric should have a list of options below it.

It doesnt in SC docs:

<img width="472" alt="Screenshot 2022-02-19 at 13 27 19" src="https://user-images.githubusercontent.com/1531144/154802739-5f250c17-5bb4-4594-a129-e5f10c84f18d.png">

but it does in the RST:
<img width="418" alt="Screenshot 2022-02-19 at 13 28 11" src="https://user-images.githubusercontent.com/1531144/154802782-d086adeb-63c1-4796-b915-8f7dd725530e.png">

**Comment by tremblap** [comment]
we had problems with this in the max doc before - I,m not equiped to download the nightlies now but is it rendering ok in max and pd?

**Comment by weefuzzy** [comment]
what about the intermediate stage – i.e. the source of the schelp? Is there some garbage there, or is it simply missed out?

**Comment by tedmoore** [comment]
It's not in the rendered `.schelp`s

**Comment by weefuzzy** [comment]
because it's not handled by the template...

**Comment by tedmoore** [comment]
Fixed by https://github.com/flucoma/flucoma-docs/pull/85
